---

  - name: add key
    apt_key: "keyserver={{ docker_repo_key_server }} id={{ docker_repo_key }}"
    become: true

  - name: apt sources
    template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list
    become: true

  - name: kernel extras
    apt: name={{ item }} state=installed update_cache=yes install_recommends=no
    with_items:
      - "linux-image-extra-{{ ansible_kernel }}"
      - linux-image-extra-virtual
    become: true

  - name: install engine
    apt: name=docker-engine state=installed update_cache=yes install_recommends=no
    become: true

  - name: add user
    user: name={{ remote_user }} groups=docker append=yes
    become: true

