---
# install and configure etcd

  - name: copy flanneld network config
    template: src=flanneld/flannel-config.json.j2 dest=/srv/flannel-config.json
    become: true

  - name: set flannel config in etcd
    shell: docker exec etcd-v3.1.3 /bin/sh -c 'etcdctl set /kubernetes/network < /etcd-data/flannel-config.json'
    become: true
