---
# install and configure etcd

  - name: stat etcd
    stat: path=/usr/bin/etcd
    register: etcd_bin

  - name: create etcd temp dir
    file: "path={{ etcd_temp_dir }} state=directory"
    when: not etcd_bin.stat.exists

  - name: download etcd
    get_url: "url={{ etcd_bin_url }} dest={{ etcd_temp_dir }}/etcd.tar.gz"
    when: not etcd_bin.stat.exists

  - name: unarchive
    unarchive: "src={{ etcd_temp_dir }}/etcd.tar.gz dest={{ etcd_temp_dir }} remote_src=yes"
    when: not etcd_bin.stat.exists

  - name: copy etcd bins
    copy: "src={{ etcd_temp_dir }}/etcd-v{{ etcd_version }}-linux-amd64/etcd dest=/usr/bin/etcd remote_src=yes mode=0755"
    when: not etcd_bin.stat.exists
    become: true

  - name: copy etcd bins
    copy: "src={{ etcd_temp_dir }}/etcd-v{{ etcd_version }}-linux-amd64/etcdctl dest=/usr/bin/etcdctl remote_src=yes mode=0755"
    when: not etcd_bin.stat.exists
    become: true

  - name: cleanup etcd install
    file: "path={{ etcd_temp_dir }} state=absent"

  - name: create etcd group
    group: name=etcd state=present gid=2379

  - name: create etcd user
    user: name=etcd comment="etcd service user" uid=2379 group=etcd

  - name: etcd conf dir
    file: "path={{ etcd_conf_dir }} state=directory"
    become: true

  - name: etcd config
    copy: "src=etcd/etcd.env dest={{ etcd_env_file }}"
    notify: etcd restart
    become: true

  - name: etcd systemd conf
    copy: src=etcd/etcd.service dest=/etc/systemd/system/etcd.service mode=644
    become: true
    notify:
        - systemd reload
        - etcd restart


