---
# install and configure etcd

  - name: install etcd
    apt: name=etcd state=installed update_cache=yes install_recommends=no
    become: true
    tags:
        - etcd

  - name: etcd config
    copy: src=etcd.env dest=/etc/default/etcd
    notify: etcd restart
    become: true
    tags:
        - etcd

  - name: etcd conf dir
    file: path=/etc/etcd state=directory
    become: true

  - name: flannel conf file
    template: src=flannel-config.json.j2 dest=/etc/etcd/flannel-config.json
    become: true

  - meta: flush_handlers

  - name: load flannel conf
    shell: "etcdctl set {{ flannel_etcd_key }} < /etc/etcd/flannel-config.json"
