---
# install and configure etcd

  - name: install etcd
    apt: name=etcd state=installed update_cache=yes install_recommends=no
    become: true
    tags:
        - etcd

  - name: etcd config
    file: src=etcd.env dest=/etc/default/etcd
    notify: etcd restart
    become: true
    tags:
        - etcd

