---

  - name: stat flanneld
    stat: path=/usr/bin/flanneld
    register: flanneld_bin

  - name: download flanneld
    get_url: "url={{ flanneld_bin_url }} dest=/usr/bin/flanneld mode=0755 force=no"
    when: not flanneld_bin.stat.exists and not flanneld_bin.skipped
    become: true

  - name: create flanneld conf dir
    file: "path={{ flanneld_conf_dir }} state=directory"
    become: true

  - name: flanneld env file
    template: "src=flanneld/flanneld.env.j2 dest={{ flanneld_env_file }}"
    notify: flanneld restart
    become: true

  - name: flanneld systemd conf
    copy: src=flanneld/flanneld.service dest=/etc/systemd/system/flanneld.service mode=644
    become: true
    notify:
        - systemd reload
        - flanneld restart

  - name: start flanneld
    service: name=flanneld state=started enabled=yes
    become: true

  - meta: flush_handlers

  - name: conf docker with flanneld
    copy: src=docker/docker.service dest=/lib/systemd/system/docker.service mode=644
    become: true
    notify:
        - systemd reload
        - docker restart
