---

  - name: stat flanneld
    stat: path=/usr/bin/flanneld
    register: flanneld_bin

  - name: create flanneld temp dir
    file: "path={{ flanneld_temp_dir }} state=directory"
    when: not flanneld_bin.stat.exists

  - name: download flanneld
    get_url: "url={{ flanneld_bin_url }} dest={{ flanneld _temp_dir }}/flanneld.tar.gz"
    when: not flanneld_bin.stat.exists

  - name: unarchive
    unarchive: "src={{ flanneld _temp_dir }}/flanneld.tar.gz dest={{ flanneld _temp_dir }} remote_src=yes"
    when: not flanneld_bin.stat.exists

  - name: copy flanneld bins
    copy: "src={{ flanneld _temp_dir }}/flanneld dest=/usr/bin/flanneld remote_src=yes mode=0755"
    when: not flanneld_bin.stat.exists
    become: true

  - name: cleanup flanneld install
    file: "path={{ flanneld _temp_dir }} state=absent"

  - name: create flanneld conf dir
    file: "path={{ flanneld_conf_dir }} state=directory"
    become: true

  - name: copy flanneld network config
    template: src=flanneld/flannel-config.json.j2 dest=/etc/flanneld/flannel-config.json
    become: true

  - name: flanneld env file
    template: "src=flanneld/flanneld.env.j2 dest={{ flanneld_env_file }}"
    notify: flanneld restart
    become: true

  - name: flanneld systemd conf
    copy: src=flanneld/flanneld.service dest=/etc/systemd/system/flanneld.service mode=644
    become: true
    notify:
        - systemd reload
        - etcd restart


