---

  - name: stat flanneld
    stat: path=/usr/bin/flanneld
    register: flanneld_bin

  - name: download flanneld
    get_url: "url={{ flanneld_bin_url }} dest=/tmp/flanneld.tar.gz"
    when: not flanneld_bin.stat.exists

  - name: create flanneld temp dir
    file: path=/tmp/flanneld state=directory
    when: not flanneld_bin.stat.exists

  - name: unarchive
    unarchive: src=/tmp/flanneld.tar.gz dest=/tmp/flanneld remote_src=yes
    when: not flanneld_bin.stat.exists

  - name: copy flanneld bins
    copy: src=/tmp/flannel/flanneld dest=/usr/bin/flanneld remote_src=yes mode=0755
    when: not flanneld_bin.stat.exists
    become: true

  - name: cleanup flanneld install
    file: path=/tmp/flanneld.tar.gz state=absent
  - file: path=/tmp/flanneld state=absent

  - name: create flanneld conf dir
    file: path=/etc/flanneld state=directory
    become: true

  - name: copy flanneld network config
    template: src=flanneld/flannel-config.json.j2 dest=/etc/flanneld/flannel-config.json
    become: true

  - name: flanneld env file
    template: src=flanneld/flanneld.env.j2 dest=/etc/default/flanneld
    notify: flanneld restart
    become: true

  - name: flanneld systemd conf
    copy: src=flanneld/flanneld.service dest=/etc/systemd/system/flanneld.service mode=644
    become: true
    notify:
        - systemd reload
        - etcd restart


