---

  - name: stat flanneld
    stat: path=/usr/bin/flanneld
    register: flanneld_bin

  - name: create flanneld temp dir
    local_action: "file path={{ flanneld_temp_dir }} state=directory"
    run_once: true
    when: not flanneld_bin.stat.exists

  - name: download flanneld
    local_action: "get_url url={{ flanneld_bin_url }} dest={{ flanneld_temp_dir }}/flanneld.tar.gz force=no"
    run_once: true
    when: not flanneld_bin.stat.exists

  - name: unarchive
    local_action: "unarchive src={{ flanneld_temp_dir }}/flanneld.tar.gz dest={{ flanneld_temp_dir }}"
    run_once: true
    when: not flanneld_bin.stat.exists

  - name: copy flanneld bins
    copy: "src={{ flanneld_temp_dir }}/flanneld dest=/usr/bin/flanneld mode=0755"
    when: not flanneld_bin.stat.exists
    become: true

  - name: create flanneld conf dir
    file: "path={{ flanneld_conf_dir }} state=directory"
    become: true

  - name: flanneld env file
    template: "src=flanneld/flanneld.env.j2 dest={{ flanneld_env_file }}"
    notify: flanneld restart
    become: true

  - name: flanneld systemd conf
    copy: src=flanneld/flanneld.service dest=/etc/systemd/system/flanneld.service mode=644
    become: true
    notify:
        - systemd reload
        - flanneld restart

  - name: start flanneld
    service: name=flanneld state=started enabled=yes
    become: true

  - meta: flush_handlers

  - name: conf docker with flanneld
    copy: src=docker/docker.service dest=/lib/systemd/system/docker.service mode=644
    become: true
    notify:
        - systemd reload
        - docker restart
