---
# tasks file for kube

  - name: install etcd
    include: etcd.yml
    when: etcd|default(false)|bool == true

  - name: install docker
    include: docker.yml
    when: docker|default(false)|bool == true

  - name: install flanneld
    include: flanneld.yml
    when: docker|default(false)|bool == true
