---
# tasks file for kube

  - name: install etcd
    include: etcd.yml
    when: etcd|default(false)|bool == true

  - name: install docker
    include: docker.yml

  - name: install flannel
    include: flannel.yml
