---

  - name: download kubernetes clients
    local_action: "get_url url={{ kubernetes_client_bin_url }} dest={{ kubernetes_temp_dir }}/kubernetes.tar.gz force=no"
    run_once: true

  - name: untar kubernetes archive
    local_action: "unarchive src={{ kubernetes_temp_dir }}/kubernetes.tar.gz dest={{ kubernetes_temp_dir }}/ creates={{ kubernetes_temp_dir }}/kubernetes"
    run_once: true

